repos:
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.9
- repo: https://gitlab.com/pycqa/flake8
  rev: main
  hooks:
    - id: flake8
- repo: https://github.com/rtts/djhtml
  rev: main
  hooks:
    - id: djhtml
