repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9
  - repo: https://github.com/rtts/djhtml
    rev: main
    hooks:
      - id: djhtml
